"""creating tables

Revision ID: 64a6f612c80d
Revises: 
Create Date: 2020-10-16 17:23:59.049943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64a6f612c80d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_urgency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('urgency', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_department', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_department'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_staff', sa.Integer(), nullable=True),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('id_status', sa.Integer(), nullable=False),
    sa.Column('id_urgency', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['client.id'], ),
    sa.ForeignKeyConstraint(['id_staff'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['id_status'], ['ticket_status.id'], ),
    sa.ForeignKeyConstraint(['id_urgency'], ['ticket_urgency.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('id_ticket', sa.Integer(), nullable=False),
    sa.Column('received_date', sa.DateTime(), nullable=True),
    sa.Column('is_incoming', sa.Boolean(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_client'], ['client.id'], ),
    sa.ForeignKeyConstraint(['id_ticket'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_message', sa.Integer(), nullable=False),
    sa.Column('attachment', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_message'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachment')
    op.drop_table('message')
    op.drop_table('ticket')
    op.drop_table('staff')
    op.drop_table('ticket_urgency')
    op.drop_table('ticket_status')
    op.drop_table('department')
    op.drop_table('client')
    # ### end Alembic commands ###
