"""Add login fields for Staff table

Revision ID: feae4e4fcf25
Revises: 64a6f612c80d
Create Date: 2020-11-01 12:16:57.726157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feae4e4fcf25'
down_revision = '64a6f612c80d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachment', 'id_message',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'attachment', type_='foreignkey')
    op.create_foreign_key(None, 'attachment', 'message', ['id_message'], ['id'])
    op.drop_column('attachment', 'id_ticket')
    op.add_column('staff', sa.Column('username', sa.String(length=64), nullable=True))
    op.alter_column('staff', 'id_department',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('staff', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('staff', 'password',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('staff', 'role',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_staff_role'), 'staff', ['role'], unique=False)
    op.create_index(op.f('ix_staff_username'), 'staff', ['username'], unique=True)
    op.drop_index('ix_staff_login', table_name='staff')
    op.drop_column('staff', 'login')
    op.add_column('ticket', sa.Column('comments', sa.String(), nullable=True))
    op.add_column('ticket', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('ticket', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('content', sa.TEXT(), nullable=True))
    op.drop_column('ticket', 'description')
    op.drop_column('ticket', 'comments')
    op.add_column('staff', sa.Column('login', sa.VARCHAR(length=64), nullable=False))
    op.create_index('ix_staff_login', 'staff', ['login'], unique=1)
    op.drop_index(op.f('ix_staff_username'), table_name='staff')
    op.drop_index(op.f('ix_staff_role'), table_name='staff')
    op.alter_column('staff', 'role',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('staff', 'password',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('staff', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('staff', 'id_department',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('staff', 'username')
    op.add_column('attachment', sa.Column('id_ticket', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'attachment', type_='foreignkey')
    op.create_foreign_key(None, 'attachment', 'ticket', ['id_ticket'], ['id'])
    op.alter_column('attachment', 'id_message',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
